- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  tags:
    - always
  tasks:
  - import_role:
      name: confluent.common
  - import_role:
      name: confluent.kerberos
    when: security_mode in ["kerberos", "kerberos_ssl", "kerberos_ssl_customcerts"] and kerberos_configure|bool

# Run the cert generation on the first zookeeper instance, which has java
- name: Certificate Generation
  hosts: zookeeper[0]
  gather_facts: no
  tags:
    - always
  tasks:
  - import_role:
      name: confluent.ssl_customcerts
    when: security_mode in ["kerberos_ssl_customcerts", "ssl_customcerts"]
  - import_role:
      name: confluent.ssl_CA
    when: security_mode in ["ssl", "sasl_ssl", "kerberos_ssl"]

- name: Certificate Syncing
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  tags:
    - always
  tasks:
  - import_role:
      name: confluent.ssl_sync
    when: security_mode in ["kerberos_ssl_customcerts", "ssl_customcerts", "ssl", "sasl_ssl", "kerberos_ssl"]

- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: no
  tags:
    - zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: no
  tags:
    - kafka_broker
  tasks:
  - import_role:
      name: confluent.kafka_broker

- name: Schema Registry Provisioning
  hosts: schema_registry
  gather_facts: no
  tags:
    - schema_registry
  tasks:
  - import_role:
      name: confluent.schema_registry

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: no
  tags:
    - kafka_connect
  tasks:
  - import_role:
      name: confluent.kafka_connect

- name: KSQL Provisioning
  hosts: ksql
  gather_facts: no
  tags:
    - ksql
  tasks:
  - import_role:
      name: confluent.ksql

- name: Control Center Provisioning
  hosts: control_center
  gather_facts: no
  tags:
    - control_center
  tasks:
  - import_role:
      name: confluent.control_center

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  gather_facts: no
  tags:
    - kafka_rest
  tasks:
  - import_role:
      name: confluent.kafka_rest

- name: Monitoring Provisioning
  hosts: monitoring
  tags:
    - monitoring
  tasks:
  - import_role:
      name: cloudalchemy.prometheus
  - import_role:
      name: cloudalchemy.grafana

- name: System Monitoring Provisioning
  hosts: system_monitoring
  tags:
    - system_monitoring
  tasks:
  - import_role:
      name: cloudalchemy.node-exporter
