all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_user: ubuntu
    ansible_become: true

    ## Required var, with options plaintext, ssl, sasl_ssl, ssl_customcerts, kerberos_ssl, kerberos, kerberos_ssl_customcerts
    security_mode: plaintext
    confluent:
      support:
        metrics_enabled: false
        customer_id: ""
      repo_version: 5.3
      package_version: 5.3.1-1 #5.3.0-1
    install_java: true #Disable if you wish to get Java from elsewhere
    jolokia_enabled: false #Disables Jolokia download/install
    jolokia_jar_path: /opt/jolokia/jolokia.jar #Needed regardless of Jolokia being enabled
    jmxexporter_enabled: true # Enabled jmx exporter
    kerberos: #Even though we aren't using Kerberos. We currently have to define this.
      keytab_dir: /etc/security/keytabs
    open_file_limit: 100000000 #Sets file limits for everything
    zookeeper:
      properties:
        clientPort: 2181

    ## Required vars for any kerberos install
    # kerberos:
    #   realm: confluent.example.com
    #   kdc_hostname: <hostname of machine with KDC installed ex. ip-172-31-45-82.us-east-2.compute.internal>
    #   admin_hostname: <hostname of machine with KDC installed ex. ip-172-31-45-82.us-east-2.compute.internal>
    #   keytab_source_dir: <path to your keytabs, ex. /root/keytabs/, note the / at the end is mandatory>

    ## Required vars for customcerts install
    # ssl_ca_certificate: <ca certificate name, eg. ca-cert>
    # ssl_host_key: <host certificate name, eg. cert-signed>
    # ssl_private_key: <private key file name, must be pkcs format, eg. keystore.p12>
    # ssl_ca_certificate_path: <full path to the ca certificate on the host you are running the plabook from, eg. /var/ca-cert>
    # ssl_host_key_path: <full path to the ca certificate on the host you are running the plabook from, eg. /var/cert-signed>
    # ssl_private_key_path: <full path to the ca certificate on the host you are running the plabook from, eg. /var/keystore.p12>
    # host_keystore_storepass: <desired password fore each key-store>
    # host_truststore_storepass: <desired password for each trust-store>
    # ca_cert_password: <password for the ca certificate>
    # host_cert_password: <password for the host certificate>
    # privatekey_keystore_password: <password for the private key key-store (pkcs12 file)>

    ## To set custom properties for each service
    ## Find property options in the Confluent Documentation
    # zookeeper:
    #   properties:
    #     initLimit: 6
    #     syncLimit: 3
    # kafka_broker:
    #   properties:
    #     num.io.threads: 15
    # schema_registry:
    #   properties:
    #     key: val
    # control_center:
    #   properties:
    #     key: val
    # kafka_connect:
    #   properties:
    #     key: val
    # kafka_rest:
    #   properties:
    #     key: val
    # ksql:
    #   properties:
    #     key: val

zookeeper:
  hosts:
    ec2-34-252-132-135.eu-west-1.compute.amazonaws.com:
      ## By default the first host will get zookeeper id=1, second gets id=2. Set zookeeper_id to customize
      # zookeeper_id: 2
    ec2-34-244-107-103.eu-west-1.compute.amazonaws.com:
      # zookeeper_id: 3
    ec2-52-209-240-157.eu-west-1.compute.amazonaws.com:
      # zookeeper_id: 1
  vars:
    kafka_broker_jolokia_port: 7771 #Needed regardless of Jolokia being enabled
    kafka_broker_jmxexporter_port: 9100
kafka_broker:
  hosts:
    ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:
      ## By default the first host will get broker id=1, second gets id=2. Set broker_id to customize
      # broker_id: 3
    ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:
      # broker_id: 2
    ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:
      # broker_id: 1
  vars:
    kafka_broker_jolokia_port: 7771 #Needed regardless of Jolokia being enabled
    kafka_broker_jmxexporter_port: 9100
    kafka_port: 9092
    kafka_broker:
      properties:
        num.partitions: 3
        min.insync.replicas: 2
        log.retention.hours: 3 #Adjust to desired value. Set low for test envs.
        default.replication.factor: 3
        #MetricsReport Specific Configs
        confluent.metrics.reporter.topic.partitions: 12
        confluent.metrics.reporter.topic.replicas: 3
        confluent.metrics.reporter.topic.retention.ms: 10800000 #Adjust to desired value. Set low for test envs.

control_center:
  hosts:
    ec2-63-35-216-167.eu-west-1.compute.amazonaws.com:
      control_center:
        properties:
          confluent.controlcenter.connect.cluster: ec2-52-208-171-6.eu-west-1.compute.amazonaws.com:8083
kafka_connect:
  hosts:
    ec2-52-208-171-6.eu-west-1.compute.amazonaws.com:
  vars:
    kafka_connect_jolokia_port: 7773 #Needed regardless of Jolokia being enabled
    kafka_port: 9092
    kafka_connect:
       properties:
          rest.advertised.host.name: "{{inventory_hostname}}"

monitoring:
  hosts:
    ec2-18-202-242-116.eu-west-1.compute.amazonaws.com:
  vars:
    grafana_security:
      admin_user: admin
      admin_password: admin
    ansible_os_family: ubuntu
    ansible_service_mgr: systemd
    ansible_architecture: amd64
    ansible_processor_count: 2
    prometheus_scrape_configs:
      - job_name: "prometheus"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9090"
      - job_name: "kafka"
        scrape_interval: 10s
        scrape_timeout: 10s
        static_configs:
          - targets:
              - "ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9100"
              - "ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9100"
              - "ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9100"
              - "ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101"
              - "ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101"
              - "ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101"
      - job_name: "zookeeper"
        scrape_interval: 10s
        scrape_timeout: 10s
        static_configs:
          - targets:
              - "ec2-34-252-132-135.eu-west-1.compute.amazonaws.com:9100"
              - "ec2-34-244-107-103.eu-west-1.compute.amazonaws.com:9100"
              - "ec2-52-209-240-157.eu-west-1.compute.amazonaws.com:9100"
              - "ec2-34-252-132-135.eu-west-1.compute.amazonaws.com:9101"
              - "ec2-34-244-107-103.eu-west-1.compute.amazonaws.com:9101"
              - "ec2-52-209-240-157.eu-west-1.compute.amazonaws.com:9101"
    labels:
      env: confluent-platform

system_monitoring:
  hosts:
    ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:
    ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:
    ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:
    ec2-34-252-132-135.eu-west-1.compute.amazonaws.com:
    ec2-34-244-107-103.eu-west-1.compute.amazonaws.com:
    ec2-52-209-240-157.eu-west-1.compute.amazonaws.com:
  vars:
    node_exporter_web_listen_address: "0.0.0.0:9101"
    node_exporter_enabled_collectors:
      - systemd
      - textfile
