---
# tasks to install the webproxy in the target machine

# JVM Installation and Repo Setup
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Copy the application config file
  template:
    src: application.conf.j2
    dest:  /etc/slim-kafka-webaction-proxy/application.conf
    mode: 0644
    owner: "{{webproxy.user}}"
    group: "{{webproxy.group}}"

- name: Copy the systemd config file
  template:
    src: webproxy.service.j2
    dest: /etc/systemd/system/webproxy.service
    mode: 0644
    owner: "{{webproxy.user}}"
    group: "{{webproxy.group}}"
